#+TITLE:UNIVERSITAS SCIENTIARUM article LaTeX template
#+AUTHOR:Juan David Salcedo Hernández

This document class conforms to the guidelines stipulated by /Universitas Scientiarum/
for its submissions and publications.

We recommended that this template be loaded with the following options:
#+begin_src latex
\documentclass[automatic-bibliography]{univsciauth}
#+end_src
Omit the ~automatic-bibliography~ option if you want to manually manage your
references, in which case the formatted references should be
drawn up on an individual LaTeX file, and included in the main file via the
~\input{}~ command as described in [[Bibliography management]].

This class supports an additional boolean option, ~defaultmaths~, which is set
to ~true~ by default and loads the ~xits~ maths font set. If you wish to use another
mathematical font set, just set this option to ~false~ and load your preferred font package in
the document preamble:
#+begin_src latex
\documentclass[defaultmaths=false]{univsciauth}
#+end_src

* Table of Contents :toc:
- [[#requirements][Requirements]]
- [[#usage][Usage]]
  - [[#document-preamble][Document preamble]]
  - [[#general-document-structure][General document structure]]
  - [[#figures-and-tables][Figures and tables]]
  - [[#bibliography-management][Bibliography management]]

* Requirements
The LaTeX installation process depends on your operating system of
choice, so you must check how to install all LaTeX packages depending
on your particular case.

You need a text editor supporting LaTeX, say Vim, Emacs, Sublime Text, etc.

This template expects the ~KOMA-script~ bundle to be installed on
your system. This set of packages is included by default in both TeXLive and
MikTeX.

Documents set up with this template may be compiled with any of the standard
LaTeX engines available: ~pdfLaTeX~, ~XeLaTeX~, or ~LuaLaTeX~.

* Usage
To start using this template, you can simply add the class file to your LaTeX
installation directory; this, too, depends on your operating system.

** Document preamble
The first thing we recommend is that you load any desired additional packages
right after defining the document class; most of the often used packages for
mathematical typesetting are included by default, but you may want to include
additional ones.

We strongly suggest that you use the ~siunitx~ package for writing units, since
it provides a straightforward set of macros for their standard formatting.
You may want to read this package's [[https://ctan.org/pkg/siunitx?lang=en][documentation]].

The package-loading section of your preamble may look similar to the following
example:
#+begin_src latex
% call the document class
\documentclass{univsci}

% require further packages,
% these are just some examples
\usepackage{longtable}
\usepackage{chemformula}
\usepackage{longtable}
\usepackage{ltxtable}
\usepackage{tabu}

% siunitx with configs
\usepackage[separate-uncertainty, allow-number-unit-breaks]{siunitx}
#+end_src

Once the packages are all set, you need to start formatting the document itself;
you need to define titles, authors, affiliations, etc. You can
define as many affiliations as desired, so long as they correlate to some
author; the following example should give you an idea of the general structure
of these definitions:
#+begin_src latex
\title{Your title}
\shorttitle{Running head for the document}

% the author command takes the authors'
% names and their corresponding affiliations,
% which may as well be a list
\author[1]{Author 1}
\author[1]{Author 2}
\author[1,2]{Author 3}
\shortauthor{Author 1 et al.}
\authormail{corresponding email}

\Affil{1}{Institutional affiliation 1}
\Affil{2}{Institutional affiliation 2}

% funding information, n.a. if none
\funding{n.a.}

% list of the available supplementary
% material, n.a. if none
\esmaterial{n.a.}

\doi{doi}
#+end_src

** General document structure
From here you could go on and write your document. You are expected to follow a specific
structure that is shown below:
#+begin_src latex
\begin{document}
\maketitle
\thispagestyle{firstpage}

\begin{abstract}
  Your abstract.

  \keywords{your keywords}
\end{abstract}

The rest of your document.
\end{document}
#+end_src

** Figures and tables
We highly recommend that figures and tables be placed in separate
subdirectories, for instance, ~figures/~ and ~tables/~.

Figures should then be called from the document as usual:
#+begin_src latex
\begin{figure}[htpb]
        \centering
        % path to the image
        \includegraphics[width=0.8\textwidth]{figures/Figure}
        \caption{caption}\label{fig:num}
\end{figure}
#+end_src

As for tables, you may want to use the ~\input{}~ command:
#+begin_src latex
\begin{table}[htpb]
        \centering
        \caption{caption}\label{tab:num}
        % Table.tex is expected to
        % contain the table code exclusively
        \input{tables/Table.tex}
\end{table}
#+end_src

For cross-references to both tables and figures, you should use either
~\autoref{tab:num}~ or ~\autoref{fig:ref}~.

** Bibliography management
In general, it is desirable to have your references automatically formatted. You
can achieve this by loading the class as is recommended and drawing up a
~bib~ file containing your references. You just need to specify this ~bib~ file
in your preamble with the following command:
#+begin_src latex
\addbibresource{references.bib}
#+end_src
Then, at the end of your document, you can print your references with this command:
#+begin_src latex
\printbibliography
#+end_src

If you so desire, references could be manually formatted; in this case we suggest
that you create a new individual file, say ~bibliography.tex~, which should be
formatted as follows:
#+begin_src latex
\begin{thebibliography}{99}
  \bibitem{1} Formatted reference here.

  \bibitem{2} Formatted reference here.
\end{thebibliography}
#+end_src

In either case, you must use the ~\cite{}~ command to typeset the references within your text.
